### ISSUE TITLE
Click TODO

### ISSUE THREAD

**Issue by natefoo** [natefoo/gravity#1]
- [ ] Implement `$GRAVITY_STATE_DIR` and `--state-dir`
- [ ] Clean up messy use of `contextlib.contextmanager` decorator
- [ ] Implement `-p/--python-exe`
